export const TEST_REDUX_LISTEN = "app/TEST_REDUX_LISTEN";
export const TEST_REDUX_SUCCESS = "app/TEST_REDUX_SUCCESS";

export const CONNECT_WEB3_LISTEN = "app/CONNECT_WEB3_LISTEN";
export const CONNECT_WEB3_SUCCESS = "app/CONNECT_WEB3_SUCCESS";
export const CONNECT_WEB3_FAIL = "app/CONNECT_WEB3_FAIL";